### ISSUE TITLE
Disable template for certain plugins

### ISSUE THREAD

**Issue by emoshaya-cognito** [JoelJ/ez-templates#55]
In the master template, I am using the sidebar link plugin. https://wiki.jenkins-ci.org/display/JENKINS/Sidebar-Link+Plugin 

However, for every job implementing this template I need to have a unique url. There is no way to parameterise this url as this is a sidebar link for the project as this is a persistent link for every project. I also have the same issue using the github pull request builder plugin https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin

I need to be able to have a unique url for every implemented project. But the template overrides these values...

![cognitoiqscreenshot2](https://cloud.githubusercontent.com/assets/8818542/11652183/34fcd496-9d8e-11e5-9486-f7494ad781bb.jpg)
![cognitoiqscreenshot1](https://cloud.githubusercontent.com/assets/8818542/11652185/37485004-9d8e-11e5-8218-34a89d036cba.jpg)

**Comment by emoshaya-cognito** [comment]
The same goes for each project's Display name... I don't want the implemented job to inherit the display name set in the master template..


![cognitoiqscreenshot3](https://cloud.githubusercontent.com/assets/8818542/11652607/8de188a2-9d90-11e5-85cf-7d3bacd557be.jpg)

**Comment by drekbour** [comment]
Raised #55 for the display name as it's clearly a bug.

Regards sidebar - I have never used this plugin but have you _tried_ parameterising it? There are quite a few fields that appear not to take job params but actually work just fine.
1. In the template, define a job property **LINK_URL** and set the sidebar "Link URL" field to **$LINK_URL**.
2. In each implementation, leave the "Link URL" field as is - just edit **LINK_URL** job property.

**Comment by emoshaya-cognito** [comment]
yeah unfortunately, the sidebar plugin as well as the github pull requester plugin where you put the github url are not parameterised...I tried your suggestion and unfortunately the $URL variable does not get expanded... The github project field is the really important one as the repository browser view will use this url to redirect users to the github repo commits..

**Comment by emoshaya-cognito** [comment]
Also parameters created in the job are undefined outside of a job execution, so if it's specifically that is the issue with the sidebar link and github project plugins. These links are static so that the link is accessible outside of the job execution.

**Comment by drekbour** [comment]
Ok, I hear the problem (#56 fixed by the way). EZ's solution doesn't scale well across plugins as it gains popularity  - most requests here are to *not* synchronize something.

@JoelJ Your thoughts are requested on the below plan. Will it actually **work**?

1. Hold a register of Xpaths which are to be retained across the synchronisation 
2. Xpaths are grouped with a name and description
3. Group name + description is shown in the UI as a check box for the user to decide on

4. :question: An extension is to provide a "condition" on a group which allows the UI to present options based on detected plugins.
5. :question: Another extension provides user-entered Groups where advanced users can define their own xpaths to work around currently unhandled issues. A quick link will allow them to submit their work as an Issue on Github.

Thoughts:
* :+1: Does not require ez to import other plugins or require binary changes to support every other plugin people use
* :+1: Still "ez" for normal users
* :+1: Can be extended locally by advanced users without binary changes and releases
* :+1: Encourages community submissions
* :-1: Not using another plugin's code model is slightly more brittle against it changing it's XML structure.

**Comment by emoshaya-cognito** [comment]
@drekbour Really love this idea and hope it gets implemented soon. This plugin has saved us many hours having to update individual jobs for minor changes across. I really appreciate your help!

**Comment by drekbour** [comment]
Above idea is a V2 level change - I envisage at least a man-week of development to get to a working prototype. In OSS-time that could be a while :)

**Comment by arpit-nagar** [comment]
Facing the same issue.
Do you have any rough timeline for v2?

**Comment by arpit-nagar** [comment]
If you need any help, I will be happy to help you.

**Comment by drekbour** [comment]
Hi. I started then got distracted by real life.

I've had a think through my idea this morning and a basic implementation (supporting _replace_ only) is entirely feasible. Supporting addition/deletion of XML portions is massively harder and might just not be required if we supply "no-op" BuildSteps (which can be _replaced_). I think I can get an alpha out in a few weeks and go from there.

**Comment by arpit-nagar** [comment]
Thanks @drekbour,
If you need any help please let me know.

**Comment by emoshaya** [comment]
Sounds great !!

**Comment by arpit-nagar** [comment]
@drekbour Is there any updates on POC?

**Comment by drekbour** [comment]
Prep work for 1.3.x is well under way. This makes it a little easier to add new template exclusions without needing the full XML-level templating.

Adding you as a collab on my own repo. Look at the 1.3.x changes (beware I'm still changing history on there so do NOT work on top of it!). If you create a 1.4.x branch (from master) and add a few items like NoOpBuildStep, NoOpPublisher etc (confirm they can be used in template jobs and have no affect on the build). We'll be able to add a fairly simple NoOpBuildStepExclusion class once 1.3.x is delivered.
