### ISSUE TITLE
Make 'Sync Source Control Mgmt' true by default

### ISSUE THREAD

**Issue by turnipski** [JoelJ/ez-templates#58]
Or at least mention that this needs to be ticked on the front page. I just wasted at least an hour trying to figure out why this build step wasn't synchronizing. It wasn't exactly helped by the fact that the 'advanced' button was off screen.

Thanks for your work on this amazing plug-in!

**Comment by drekbour** [comment]
This was the default when #36, #38 was merged and I agree it should be the standard. @brantone removed his own defaulting for some reason in 66c1dc682a176289652f9d69958e2c98340310aa. Please put it back (via a PR to the *new* repo https://github.com/jenkinsci/ez-templates-plugin)

**Comment by Brantone** [comment]
My reasoning was : the typical purpose for using this plugin is to have similar build steps but for different projects, and since different projects are most often in different repos than default to not sync SCM. Granted the job could be set up with parameters for SCM, but that'll only work at a high-level ... and won't work at all if (in my use case) different projects are in different SCM types altogether (ex: some in Perforce, some in Git). But, whatever works, just a checkbox either way :)

**Comment by drekbour** [comment]
FYI I already amended this one, no further work required. I get what you're saying about different projects but I imagine its perfectly common for all impls to share the same scm provider. The out-of-the-box behaviour needs to remain as advertised (clone except job params) until we manage to get something working for the V2 stream that allows us to avoid the ugly way we have implement each specialisation.
